rm:
	rm partition0/*.txt partition0/init partition0/app_checkChain partition0/app_checkLog partition0/app_checkMoney partition0/app_transaction
	rm partition1/*.txt partition1/init partition1/app_checkChain partition1/app_checkLog partition1/app_checkMoney partition1/app_transaction
	rm partition2/*.txt partition2/init partition2/app_checkChain partition2/app_checkLog partition2/app_checkMoney partition2/app_transaction

